CloudFrontOriginIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "origin identity"

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: niyibizi-patrick
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:068159783898/CloudFront Origin Access Identity ${CloudFrontOriginIdentity}"
            Action: "s3:GetObject"
            Resource: arn:aws:s3:::niyibizi-patrick/*

  CloudfrontDistro:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
        - pail.live
        - www.pail.live
        DefaultCacheBehavior:
          AllowedMethods:
          - "GET"
          - "HEAD"
          - "OPTIONS"
          DefaultTTL: 3600
          ForwardedValues:
            QueryString: "true"
            Cookies:
              Forward: "none"
          TargetOriginId: "S3Origin"
          ViewerProtocolPolicy: "redirect-to-https"
        DefaultRootObject: "index.html"
        Enabled: "true"
        HttpVersion: http2
        Origins:
        - Id: "S3Origin"
          DomainName: bitama-patrick.s3.amazonaws.com
          S3OriginConfig:
            OriginAccessIdentity: !Join ["", ["origin-access-identity/cloudfront/", !Ref OriginAccessIdentity]]
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          MinimumProtocolVersion: "TLSv1.2_2018"
          SslSupportMethod: "sni-only"

  DomainDns:
    Type: "AWS::Route53::RecordSet"
    DependsOn: CloudfrontDistro
    Properties:
      AliasTarget:
        DNSName: !GetAtt CloudfrontDistro.DomainName
        HostedZoneId: "Z2FDTNDATAQYW2"
      HostedZoneName: pail.live.
      Name: pail.live
      Type: "A"

  DomainDnsWww:
    Type: "AWS::Route53::RecordSet"
    DependsOn: CloudfrontDistro
    Properties:
      AliasTarget:
        DNSName: !GetAtt CloudfrontDistro.DomainName
        HostedZoneId: "Z2FDTNDATAQYW2"
      HostedZoneName: pail.live.
      Name: www.pail.live
      Type: "A"